### ISSUE TITLE
Consistent Actor Identification

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-scitt/charter#14]
I do not think this change is an improvement. 

https://github.com/ietf-scitt/charter/blob/master/ietf-scitt-charter.md#establish-consistent-identity-format-for-actors

I'd actually keep it as it was and change it back.

"Establish consistent Identity Format for Actors" => "Consistent Actor Identification"

I'll create a corresponding PR. Please resolve the issue with commits and comments on that PR.

**Comment by nealmcb** [comment]
Given that the PR was merged, and noting that it didn't have a "Fixes xxx" comment, it looks like this issue can be closed.....

**Comment by henkbirkholz** [comment]
yes, this can be closed!
