### ISSUE TITLE
References to other related work?

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-scitt/charter#5]
From @OR13:

https://github.com/ietf-scitt/charter/pull/3#discussion_r908644534

> I would like to coordinate with W3C WGs as well, specifically the DID WG and the VC WG.

**Comment by OR13** [comment]
I'm happy to be assigned this item, I'm not sure of the IETF formal process regarding this, but I am happy to take either a formal or informal role in this context.

**Comment by henkbirkholz** [comment]
The RATS charter dedicates a single but quite clear sentence to that respect, I think:

> The WG will [...] cooperate and coordinate with other IETF WGs such as TEEP and SUIT, and work with organizations in the community, such as the TCG, Global Platform, and the FIDO Alliance, as appropriate.

So maybe something like this as a starter?

> The WG will cooperate and coordinate with other IETF WGs such as COSE and RATS, and work with organizations in the community, such as the TCG, W3C, or the OpenSSF, as appropriate.

**Comment by OR13** [comment]
I agree, do we apply labels like "ready-for-pr" here?
