### ISSUE TITLE
"develop standards" deliverables might need more detail

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-scitt/charter#7]
https://github.com/ietf-scitt/charter/pull/3#issuecomment-1168500475

> The first occurrence of "The WG will develop standards" needs a little bit more flesh to the bones, I think. Right now, this could mean a lot of things, such as protocols, or trust relationships, or security flows.

**Comment by OR13** [comment]
@henkbirkholz anything I can do to help flush this out?

**Comment by henkbirkholz** [comment]
@OR13 thanks for the help! My assumption is that [fb3b675](https://github.com/ietf-scitt/charter/commit/fb3b675ee48209e39428e28669838f2a62b52fd9) includes all changes proposed? If you confirm, we can close this issue.

**Comment by OR13** [comment]
Good to close imo.
